// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "barcodedecoder1.h"

/////////////////////////////////////////////////////////////////////////////
// CBarcodedecoder1

IMPLEMENT_DYNCREATE(CBarcodedecoder1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CBarcodedecoder1 properties

/////////////////////////////////////////////////////////////////////////////
// CBarcodedecoder1 operations
